services:
  typescript-backend:
    image: node:18-alpine
    container_name: typescript-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install pnpm -g && pnpm install && rm -rf build && pnpm run build && pnpm run start:dev"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - dev

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST_CACHE_SIZE=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 82:8080
    profiles:
      - dev

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
  redis_data:
